server:
  port: 9191

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: http://auth-service:9000/
          predicates:
            - Path=/auth-api/**
        - id: master-service
          uri: http://master-service:9001/
          predicates:
            - Path=/masters/**
        - id: customer-service
          uri: http://customer-service:9002/
          predicates:
            - Path=/customers/**
        - id: product-service
          uri: http://product-service:9003/
          predicates:
            - Path=/products/**
  profiles:
    active:
      - path # path | header | query are the other spring profiles for other strategies

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka # value will get overriden if passed from external config

logging:
  level:
     web: debug
